export const italian = [
    'fuggedaboutit',
    'little italy',
    'sicily',
    'naples',
    'rome',
    'calabria',
    'brooklyn',
    'jersey',
    'family',
    'tradition',
    'catholic',
    'sunday dinner',
    'pasta',
    'wine',
    'espresso',
    'bocce',
    'vespa',
    'opera',
    'fiat',
    'renaissance',
    'columbus',
    'pizza',
    'pasta',
    'spaghetti',
    'lasagna',
    'ravioli',
    'fettuccine',
    'cannoli',
    'espresso',
    'cappuccino',
    'mozzarella',
    'parmesan',
    'prosciutto',
    'salami',
    'bruschetta',
    'marinara',
    'olive oil',
    'garlic',
    'tomato sauce',
    'meatballs',
    'basil',
    'ricotta',
    'gnocchi',
    'the godfather',
    'the sopranos',
    'goodfellas',
    'mafia',
    'mobster',
    'don',
    'capo',
    'wiseguy',
    'gangster',
    'tony soprano',
    'vito corleone',
    'al capone',
    'big italian wedding',
    'hand gestures',
    'gold chain',
    'track suit',
    'pinky ring',
    'bada bing',
    'mamma mia!',
    'scarface',
    'casino',
    'mean streets',
    'a bronx tale',
    'the irishman',
    'donnie brasco',
    'jersey shore',
    'my cousin vinny',
    'vinny gambini',
    'rocky balboa',
    'adrian pennino',
    'paulie walnuts',
    'silvio dante',
    'christopher moltisanti',
    'michael corleone',
    'frank sinatra',
    'dean martin',
    'tony bennett',
    'gotti',
    'john travolta',
    'saturday night fever',
    'bronx tale',
    'italian mob boss',
    'undercover cop in the mob',
    'slicked-back hair',
    'muscle cars',
    'old-school social clubs',
    'neighborhood social club',
    'loan shark',
    'crime family',
    'omertà',
    'hitman',
    'cement shoes',
    'meat hook',
    'strip club owner',
    'gambling ring',
    'illegal bookmaker',
    'numbers game',
    'mafioso code of silence',
    'restaurant owner with mob ties',
    'politician with mafia connections',
    'deli owner with an attitude',
    'guido',
    'tough guy with a soft side',
    'hot-tempered girlfriend',
    'loyal but dangerous best friend',
    'over-the-top hand gestures',
    'always knows a guy',
    'stereotypical brooklyn accent',
    'italian pride tattoos',
    'big italian family drama',
    'streetwise but romantic',
    'the enforcer',
    'cigar-smoking mobster',
    'limo rides to secret meetings',
    'black cadillac escalade',
    'talking in code',
    'fake business fronts',
    'speakeasies and bootlegging',
    'eating pasta while talking business',
    'loud',
    'passionate',
    'family-oriented',
    'tough',
    'protective',
    'talk with hands',
    'business owners',
    'catholic church',
    'large gatherings',
    'close-knit families',
    'overprotective parents',
    'strong accents',
    'thick hair',
    'mustache',
    'greasy hair',
    'strong opinions',
    'emotional',
    'love of food',
    'italian flag colors',
    'fast talking',
    'proud',
    'love of soccer',
    'hospitality',
    'matriarchal grandmother',
    'over-the-top weddings',
    "mama's boy",
    'strong sense of honor',
    'big sunday meals',
    'dramatic arguments',
    'lots of hugs and kisses',
    'superstitions',
    'gold jewelry',
    'nickname for everyone',
    'quick temper',
    'street smarts',
    'loyalty to friends & family',
    'loves to negotiate',
    'overloads on garlic',
    'drives a loud car',
    'always dressed sharp',
    'thick eyebrows',
    'expressive facial expressions',
    'strong love for italian soccer clubs',
    'patriotic about italy',
    'always knows a guy',
    'protective over daughters',
    'neighborhood pride',
    'stereotypical mafia ties in jokes',
    'big personalities',
    'cigars & espresso',
    'loves red wine',
    'gabagool'
]

export const severance = [
    'the work is mysterious and important',
    'innie',
    'outie',
    'lumon industries',
    'severed floor',
    'macrodata refinement',
    'mdr',
    'optics & design',
    'o&d',
    'wellness sessions',
    'break room',
    'perpetuity wing',
    'the board',
    'bobbing for pineappples',
    'overtime contingency protocol',
    'petey',
    'reintegration',
    'goat man',
    'mark s.',
    'helly r.',
    'irving b.',
    'dylan g.',
    'gemma scout',
    'harmony cobel',
    'mr. milchick',
    'ms. casey',
    'miss huang',
    'burt goodman',
    'jame eagan',
    'defiant jazz',
    'music dance experience',
    'the music dance experience is officially cancelled',
    'outdoor retreat team building occurrence',
    'ortbo',
    'calamitous ortbo',
    'egg bar social',
    'waffle party',
    'eagan philosophy',
    'kier',
    'kier be with you',
    'book of kier',
    'goat wrangling',
    'distribution supply',
    'incorrect use of paper clips',
    'ineffective kindness reforms',
    'too many big words',
    'the numbers were scary',
    'corridor maze',
    'the you you are',
    'elevator allergy song',
    'the we we are',
    'attila',
    'chikhai bardo',
    'woe\'s hollow',
    'dr. ricken lazlo hale',
    'baby goats',
    'coffee cozies',
    'finger traps',
    'i heard page 197 slaps',
    'a handshake is available on request',
    'paintball',
    'perks',
    'please try to enjoy each fact equally',
    'the four tempers',
    'woe',
    'frolic',
    'dread',
    'malice',
    'hall pass',
    'cold harbor',
    'allentown',
    'dranesville',
    'siena',
    'lucknow',
    'loveland',
    'wellington',
    'st. pierre',
    'zurich',
    'watermelon head',
    'melon party',
    'egg drop challenge',
    'kier taming the four tempers',
    'we must be cut to heal',
    'the youthful convalescence of kier',
    'kier invites you to drink his water',
    'the grim barbarity of optics and design',
    'the courtship of kier and imogen',
    'the macrodata refinement calamity',
    'kier pardons his betrayers',
    'duck-rabbit illusion',
    'recanonicalized portrait of kier',
    'your outie is generous',
    'your outie is fond of music and owns many records',
    'your outie is a friend to children and to the elderly and the insane',
    'your outie is strong and helped someone lift a heavy object',
    'your outie attends many dances and is popular among the other attendees',
    'your outie likes films and owns a machine that can play them',
    'your outie is splendid and can swim gracefully and well',
    'your outie won a game two weeks ago',
    'your outie values water',
    'a photo of your outie with a trophy was once in a newspaper',
    'your outie has no fear of muggers or knaves',
    'your outie likes the sound of radar',
    'your outie is skilled at kissing and lovemaking',
    'your outie is kind',
    'your outie has brightened people\'s days by merely smiling',
    'your outie makes time for people, even when...',
    'your outie is kind',
    'your outie can set up a tent in under three minutes',
    'your outie knows a beautiful rock from a plain one',
    'your outie can parallel park in less than 20 seconds',
    'your outie can roller-skate with grace',
    'your outie pays all of his gas and electric bills within three business days',
    'your outie listens to music while shaving, but not while showering',
    'your outie prefers two scoops of ice cream in a serving, but they must be the same flavor',
    'your outie once captured a butterfly',
    'we serve kier you child!',
    'i think people really enjoyed you tonight mark',
    'the egg bar is coveted af',
    'you are sparing with the facial encouragements',
    'i\'m self-reporting you',
    'it was only up for a month, but man, what a month',
    'bullies are nothing but bull and lies',
    'at the center of industry, is dust',
    'they cannot crucify you if your hand is in a fist',
    'three time r of the q!',
    'am i livestock?',
    'you want a hug? go to hell and find your mother',
    'there was a businessman in the yard last night',
    'machines are made of metal, whereas man is made of skin',
    'render not my creations in miniature',
    'we don\'t paint them, but we do hang them',
    'marshmallows are for team players',
]