export const italian = [
    'italy',
    'italian-american',
    'heritage',
    'ancestry',
    'immigration',
    'new york',
    'little italy',
    'sicily',
    'naples',
    'rome',
    'calabria',
    'brooklyn',
    'jersey',
    'family',
    'tradition',
    'catholic',
    'sunday dinner',
    'pasta',
    'wine',
    'espresso',
    'bocce',
    'vespa',
    'opera',
    'fiat',
    'renaissance',
    'columbus',
    'pizza',
    'pasta',
    'spaghetti',
    'lasagna',
    'ravioli',
    'fettuccine',
    'cannoli',
    'espresso',
    'cappuccino',
    'mozzarella',
    'parmesan',
    'prosciutto',
    'salami',
    'bruschetta',
    'marinara',
    'olive oil',
    'garlic',
    'tomato sauce',
    'meatballs',
    'basil',
    'ricotta',
    'gnocchi',
    'the godfather',
    'the sopranos',
    'goodfellas',
    'mafia',
    'mobster',
    'don',
    'capo',
    'wiseguy',
    'gangster',
    'tony soprano',
    'vito corleone',
    'al capone',
    'big italian wedding',
    'hand gestures',
    'gold chain',
    'track suit',
    'pinky ring',
    'bada bing',
    'fuggedaboutit',
    'mamma mia!',
    'scarface',
    'casino',
    'mean streets',
    'a bronx tale',
    'the irishman',
    'donnie brasco',
    'jersey shore',
    'my cousin vinny',
    'vinny gambini',
    'rocky balboa',
    'adrian pennino',
    'paulie walnuts',
    'silvio dante',
    'christopher moltisanti',
    'michael corleone',
    'frank sinatra',
    'dean martin',
    'tony bennett',
    'gotti',
    'john travolta',
    'saturday night fever',
    'bronx tale',
    'italian mob boss',
    'undercover cop in the mob',
    'slicked-back hair',
    'muscle cars',
    'old-school social clubs',
    'neighborhood social club',
    'loan shark',
    'crime family',
    'omertà',
    'hitman',
    'cement shoes',
    'meat hook',
    'strip club owner',
    'gambling ring',
    'illegal bookmaker',
    'numbers game',
    'mafioso code of silence',
    'restaurant owner with mob ties',
    'politician with mafia connections',
    'deli owner with an attitude',
    'guido',
    'tough guy with a soft side',
    'hot-tempered girlfriend',
    'loyal but dangerous best friend',
    'over-the-top hand gestures',
    'always knows a guy',
    'stereotypical brooklyn accent',
    'italian pride tattoos',
    'big italian family drama',
    'streetwise but romantic',
    'the enforcer',
    'cigar-smoking mobster',
    'limo rides to secret meetings',
    'black cadillac escalade',
    'talking in code',
    'fake business fronts',
    'speakeasies and bootlegging',
    'eating pasta while talking business',
    'loud',
    'passionate',
    'family-oriented',
    'tough',
    'protective',
    'talk with hands',
    'business owners',
    'catholic church',
    'large gatherings',
    'close-knit families',
    'overprotective parents',
    'strong accents',
    'thick hair',
    'mustache',
    'greasy hair',
    'strong opinions',
    'emotional',
    'love of food',
    'italian flag colors',
    'fast talking',
    'proud',
    'love of soccer',
    'hospitality',
    'matriarchal grandmother',
    'over-the-top weddings',
    "mama's boy",
    'strong sense of honor',
    'big sunday meals',
    'dramatic arguments',
    'lots of hugs and kisses',
    'superstitions',
    'gold jewelry',
    'nickname for everyone',
    'quick temper',
    'street smarts',
    'loyalty to friends & family',
    'loves to negotiate',
    'overloads on garlic',
    'drives a loud car',
    'always dressed sharp',
    'thick eyebrows',
    'expressive facial expressions',
    'strong love for italian soccer clubs',
    'patriotic about italy',
    'always knows a guy',
    'protective over daughters',
    'neighborhood pride',
    'stereotypical mafia ties in jokes',
    'big personalities',
    'cigars & espresso',
    'loves red wine',
    'gabagool'
]

export const severance = [
    'severance',
    'innie',
    'outie',
    'lumon industries',
    'severed floor',
    'macrodata refinement',
    'mdr',
    'optics & design',
    'o&d',
    'wellness sessions',
    'break room',
    'perpetuity wing',
    'the board',
    'overtime contingency protocol',
    'mark s.',
    'helly r.',
    'irving b.',
    'dylan g.',
    'gemma scout',
    'harmony cobel',
    'mr. milchick',
    'ms. casey',
    'miss huang',
    'burt goodman',
    'jame eagan',
    'defiant jazz',
    'music dance experience',
    'outdoor retreat team building occurance',
    'ortbo',
    'egg bar social',
    'waffle party',
    'eagan philosophy',
    'kier',
    'kier be with you',
    'book of kier',
    'goat wrangling',
    'distribution supply',
    'scary numbers',
    'corridor maze',
    'the you you are',
    'dr. ricken lazlo hale',
    'baby goats',
    'coffee cozies',
    'finger traps',
    'page 197 slaps',
    'a handshake is available on request',
    'paintball',
    'perks',
    'enjoy each fact equally',
    'your work is mysterious and important',
    'the four tempers',
    'woe',
    'frolic',
    'dread',
    'malice',
    'cold harbor',
    'allentown',
    'dranesville',
    'siena',
    'lucknow',
    'loveland',
    'wellington',
    'st. Pierre',
    'zurich'
]