export const latin = [
    'Lorem ipsum dolor', 'sit', 'amet', 'consectetur', 'adipiscing', 'elit',
    'sed', 'do', 'eiusmod', 'tempor', 'incididunt', 'ut', 'labore', 'et',
    'dolore', 'magna', 'aliqua', 'enim', 'ad', 'minim', 'veniam', 'quis',
    'nostrud', 'exercitation', 'ullamco', 'laboris', 'nisi', 'ut', 'aliquip',
    'ex', 'ea', 'commodo', 'consequat', 'duis', 'aute', 'irure', 'in',
    'reprehenderit', 'voluptate', 'velit', 'esse', 'cillum', 'fugiat',
    'nulla', 'pariatur', 'excepteur', 'sint', 'occaecat', 'cupidatat', 'non',
    'proident', 'sunt', 'culpa', 'qui', 'officia', 'deserunt', 'mollit',
    'anim', 'id', 'est', 'laborum', 'ac', 'accumsan', 'adipisci', 'alias',
    'aptent', 'arcu', 'auctor', 'augue', 'bibendum', 'blandit', 'class',
    'congue', 'cursus', 'dapibus', 'diam', 'dictum', 'dignissim', 'egestas',
    'eleifend', 'euismod', 'facilisi', 'facilisis', 'fames', 'fermentum',
    'feugiat', 'fringilla', 'fusce', 'gravida', 'habitant', 'habitasse',
    'hendrerit', 'himenaeos', 'iaculis', 'imperdiet', 'inceptos', 'integer',
    'interdum', 'justo', 'lacinia', 'lacus', 'laoreet', 'lectus', 'ligula',
    'litora', 'lobortis', 'luctus', 'maecenas', 'mattis', 'mauris', 'metus',
    'molestie', 'morbi', 'nam', 'natoque', 'neque', 'netus', 'nibh', 'nisi',
    'nisl', 'non', 'nostra', 'nulla', 'nullam', 'nunc', 'odio', 'orci',
    'ornare', 'pellentesque', 'penatibus', 'per', 'pharetra', 'phasellus',
    'placerat', 'platea', 'porta', 'porttitor', 'posuere', 'potenti',
    'praesent', 'pretium', 'primis', 'proin', 'pulvinar', 'purus', 'quam',
    'quis', 'quisque', 'rhoncus', 'ridiculus', 'risus', 'rutrum', 'sagittis',
    'sapien', 'scelerisque', 'sed', 'sem', 'semper', 'senectus', 'sociosqu',
    'sodales', 'sollicitudin', 'suscipit', 'suspendisse', 'taciti', 'tellus',
    'tempor', 'tempus', 'tincidunt', 'torquent', 'tortor', 'tristique',
    'turpis', 'ullamcorper', 'ultrices', 'ultricies', 'urna', 'ut', 'varius',
    'vehicula', 'vel', 'velit', 'venenatis', 'vestibulum', 'vitae', 'vivamus',
    'viverra', 'volutpat', 'vulputate'
]

export const italian = [
    'Fuggedaboutit',
    'little italy',
    'sicily',
    'naples',
    'rome',
    'calabria',
    'brooklyn',
    'jersey',
    'family',
    'tradition',
    'catholic',
    'sunday dinner',
    'pasta',
    'wine',
    'espresso',
    'bocce',
    'vespa',
    'opera',
    'fiat',
    'renaissance',
    'columbus',
    'pizza',
    'pasta',
    'spaghetti',
    'lasagna',
    'ravioli',
    'fettuccine',
    'cannoli',
    'espresso',
    'cappuccino',
    'mozzarella',
    'parmesan',
    'prosciutto',
    'salami',
    'bruschetta',
    'marinara',
    'olive oil',
    'garlic',
    'tomato sauce',
    'meatballs',
    'basil',
    'ricotta',
    'gnocchi',
    'the godfather',
    'the sopranos',
    'goodfellas',
    'mafia',
    'mobster',
    'don',
    'capo',
    'wiseguy',
    'gangster',
    'tony soprano',
    'vito corleone',
    'al capone',
    'big italian wedding',
    'hand gestures',
    'gold chain',
    'track suit',
    'pinky ring',
    'bada bing',
    'mamma mia!',
    'scarface',
    'casino',
    'mean streets',
    'a bronx tale',
    'the irishman',
    'donnie brasco',
    'jersey shore',
    'my cousin vinny',
    'vinny gambini',
    'rocky balboa',
    'adrian pennino',
    'paulie walnuts',
    'silvio dante',
    'christopher moltisanti',
    'michael corleone',
    'frank sinatra',
    'dean martin',
    'tony bennett',
    'gotti',
    'john travolta',
    'saturday night fever',
    'bronx tale',
    'italian mob boss',
    'undercover cop in the mob',
    'slicked-back hair',
    'muscle cars',
    'old-school social clubs',
    'neighborhood social club',
    'loan shark',
    'crime family',
    'omertà',
    'hitman',
    'cement shoes',
    'meat hook',
    'strip club owner',
    'gambling ring',
    'illegal bookmaker',
    'numbers game',
    'mafioso code of silence',
    'restaurant owner with mob ties',
    'politician with mafia connections',
    'deli owner with an attitude',
    'guido',
    'tough guy with a soft side',
    'hot-tempered girlfriend',
    'loyal but dangerous best friend',
    'over-the-top hand gestures',
    'always knows a guy',
    'stereotypical brooklyn accent',
    'italian pride tattoos',
    'big italian family drama',
    'streetwise but romantic',
    'the enforcer',
    'cigar-smoking mobster',
    'limo rides to secret meetings',
    'black cadillac escalade',
    'talking in code',
    'fake business fronts',
    'speakeasies and bootlegging',
    'eating pasta while talking business',
    'loud',
    'passionate',
    'family-oriented',
    'tough',
    'protective',
    'talk with hands',
    'business owners',
    'catholic church',
    'large gatherings',
    'close-knit families',
    'overprotective parents',
    'strong accents',
    'thick hair',
    'mustache',
    'greasy hair',
    'strong opinions',
    'emotional',
    'love of food',
    'italian flag colors',
    'fast talking',
    'proud',
    'love of soccer',
    'hospitality',
    'matriarchal grandmother',
    'over-the-top weddings',
    "mama's boy",
    'strong sense of honor',
    'big sunday meals',
    'dramatic arguments',
    'lots of hugs and kisses',
    'superstitions',
    'gold jewelry',
    'nickname for everyone',
    'quick temper',
    'street smarts',
    'loyalty to friends & family',
    'loves to negotiate',
    'overloads on garlic',
    'drives a loud car',
    'always dressed sharp',
    'thick eyebrows',
    'expressive facial expressions',
    'strong love for italian soccer clubs',
    'patriotic about italy',
    'always knows a guy',
    'protective over daughters',
    'neighborhood pride',
    'stereotypical mafia ties in jokes',
    'big personalities',
    'cigars & espresso',
    'loves red wine',
    'gabagool'
]

export const severance = [
    'The work is mysterious and important',
    'innie',
    'outie',
    'lumon industries',
    'severed floor',
    'macrodata refinement',
    'mdr',
    'optics & design',
    'o&d',
    'wellness sessions',
    'break room',
    'perpetuity wing',
    'the board',
    'bobbing for pineappples',
    'overtime contingency protocol',
    'petey',
    'reintegration',
    'goat man',
    'mark s.',
    'helly r.',
    'irving b.',
    'dylan g.',
    'gemma scout',
    'harmony cobel',
    'mr. milchick',
    'ms. casey',
    'miss huang',
    'burt goodman',
    'jame eagan',
    'defiant jazz',
    'music dance experience',
    'the music dance experience is officially cancelled',
    'outdoor retreat team building occurrence',
    'ortbo',
    'calamitous ortbo',
    'egg bar social',
    'waffle party',
    'eagan philosophy',
    'kier',
    'kier be with you',
    'book of kier',
    'goat wrangling',
    'distribution supply',
    'incorrect use of paper clips',
    'ineffective kindness reforms',
    'too many big words',
    'the numbers were scary',
    'corridor maze',
    'the you you are',
    'elevator allergy song',
    'the we we are',
    'attila',
    'chikhai bardo',
    'woe\'s hollow',
    'dr. ricken lazlo hale',
    'baby goats',
    'coffee cozies',
    'finger traps',
    'i heard page 197 slaps',
    'a handshake is available on request',
    'paintball',
    'perks',
    'please try to enjoy each fact equally',
    'the four tempers',
    'woe',
    'frolic',
    'dread',
    'malice',
    'hall pass',
    'cold harbor',
    'allentown',
    'dranesville',
    'siena',
    'lucknow',
    'loveland',
    'wellington',
    'st. pierre',
    'zurich',
    'watermelon head',
    'melon party',
    'egg drop challenge',
    'kier taming the four tempers',
    'we must be cut to heal',
    'the youthful convalescence of kier',
    'kier invites you to drink his water',
    'the grim barbarity of optics and design',
    'the courtship of kier and imogen',
    'the macrodata refinement calamity',
    'kier pardons his betrayers',
    'duck-rabbit illusion',
    'recanonicalized portrait of kier',
    'your outie is generous',
    'your outie is fond of music and owns many records',
    'your outie is a friend to children and to the elderly and the insane',
    'your outie is strong and helped someone lift a heavy object',
    'your outie attends many dances and is popular among the other attendees',
    'your outie likes films and owns a machine that can play them',
    'your outie is splendid and can swim gracefully and well',
    'your outie won a game two weeks ago',
    'your outie values water',
    'a photo of your outie with a trophy was once in a newspaper',
    'your outie has no fear of muggers or knaves',
    'your outie likes the sound of radar',
    'your outie is skilled at kissing and lovemaking',
    'your outie is kind',
    'your outie has brightened people\'s days by merely smiling',
    'your outie makes time for people, even when...',
    'your outie is kind',
    'your outie can set up a tent in under three minutes',
    'your outie knows a beautiful rock from a plain one',
    'your outie can parallel park in less than 20 seconds',
    'your outie can roller-skate with grace',
    'your outie pays all of his gas and electric bills within three business days',
    'your outie listens to music while shaving, but not while showering',
    'your outie prefers two scoops of ice cream in a serving, but they must be the same flavor',
    'your outie once captured a butterfly',
    'we serve kier you child!',
    'i think people really enjoyed you tonight mark',
    'the egg bar is coveted af',
    'you are sparing with the facial encouragements',
    'i\'m self-reporting you',
    'it was only up for a month, but man, what a month',
    'bullies are nothing but bull and lies',
    'at the center of industry, is dust',
    'they cannot crucify you if your hand is in a fist',
    'three time r of the q!',
    'am i livestock?',
    'you want a hug? go to hell and find your mother',
    'there was a businessman in the yard last night',
    'machines are made of metal, whereas man is made of skin',
    'render not my creations in miniature',
    'we don\'t paint them, but we do hang them',
    'marshmallows are for team players',
]

export const nyc = [
    "How you doin'?", "Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island", "Empire State Building", "Times Square",
    "Central Park", "Broadway", "The Met", "Statue of Liberty", "Wall Street", "The Village", "SoHo", "Tribeca",
    "Harlem", "Coney Island", "Little Italy", "Chinatown", "The Bronx Zoo", "Yankee Stadium", "The Apollo",
    "the big apple", "NYC Subway", "hot dog", "pretzel", "bagel", "pizza", "Junior's cheesecake",
    "pastrami on rye", "bagel and lox", "knish", "coffee", "deli", "reuben sandwich", "Italian ices",
    "chicken and rice", "halal cart", "New York slice", "street food", "food truck", "Dunkin' Donuts",
    "Broadway show", "jazz", "hip-hop", "bodega", "yellow cab", "Brooklyn Bridge", "Flatiron Building",
    "Fifth Avenue", "Staten Island Ferry", "ice skating", "NYU", "Columbia University", "Greenwich Village",
    "East Village", "Upper East Side", "Upper West Side", "Lower East Side", "The Knicks",
    "New York Mets", "NYPD", "FDNY", "the city that never sleeps", "fuggedaboutit!",
    "c'mon, I'm walkin' here!", "yo", "what's good?", "Noo Yawk", "get outta here", "schlep", "chutzpah",
    "Katz's Deli", "Lombardi's Pizza", "Halal Guys", "bodega cat", "Art Deco", "skyscraper", "street art",
    "The High Line", "The Bowery", "The LIRR", "Mets", "Yankees", "Brooklyn Nets", "New York Public Library",
    "Hudson Yards", "Chelsea Market", "subway token", "bagel with cream cheese", "egg cream", "corned beef",
    "chopped cheese sandwich", "JFK", "LaGuardia", "Grand Central Station", "Penn Station",
    "Parker's House Rolls", "Korean BBQ", "street performers", "karaoke", "The Bronx Tale", "Andy Warhol",
    "Macy's Thanksgiving Parade", "Broadway Theatre District", "dim sum", "SoHo art galleries", "Museum Mile",
    "Nathan's Famous", "pizza rat", "rent control", "rent stabilization", "standing on line", "empire state of mind",
    "Shackmeister Ale", "frosé", "bagel with a schmear", "it's showtime!", "dumplings", "metrocard", "OMNY",
    "TKTS Booth", "too few of our old crew left on Astor", "if I call you from First Avenue",
    "I want to be a part of it, New York, New York", "I wanna wake up in a city that doesn't sleep",
    "I'll make a brand new start of it in old New York", "if I can make it there, I'll make it anywhere",
    "yeah, I'm out that Brooklyn, now I'm down in Tribeca", "I used to cop in Harlem, hola, my Dominicanos",
    "let's hear it for New York", "big lights will inspire you", "there's nothing you can't do",
    "these streets will make you feel brand new", "New York, I love you, but you're bringing me down",
    "the mermaid day parade", "transfer is available to the F train",
    "backpacks and other large containers are subject to random search by the police", "the rooftop pigeon men",
    "Sake Bar Decibel", "The Strand", "loosie", "The Paradise Garage", "Shakespeare in the Park", "WNYC",
    "The Brian Lehrer Show", "Printed Matter", "scaffolding", "Scabby the Rat", "a Spike Lee joint", "Nitehawk Cinema",
    "Celebrate Brooklyn", "rent", "broker fee", "oyster happy hour", "live from New York it's Saturday night",
    "Hamilton", "Stuyvesant", "Bed-Stuy do or die", "Gothamist", "all the news that's fit to print",
    "Warriors, come out to play", "in New York, you can be a new man", "Gotham City", "concrete jungle",
    "I love New York", "New York, New York! It's a helluva town!", "beneath the Broadway lights",
    "got to see the whole town from Yonkers on down to the bay", "The Bronx is up, but the Battery's down",
    "bridge and tunnel", "get your nutcrackers", "Ess-a-Bagel", "30 Rock", "bacon egg and cheese on a roll",
    "grandma slice", "plain slice", "regular slice", "slice", "kosher deli", "Trini", "bakes and doubles",
    "deliveristas", "app delivery", "Halloween parade", "Cookie Puss", "Fudgie the Whale", "the ball drop",
    "The Library Lions", "Angels in America", "back in a New York groove",
    "you grew up ridin' the subways, running with people up in Harlem, down on Broadway",
    "talkin' that street talk", "you're a native New Yorker", "searchin' for someone to set you free from New York City",
    "love could really be like a Broadway show", "we can hitch a ride to Rockaway Beach", "stoop", "Rock-rock, Rockaway Beach",
    "New York City Boy", "turnstile", "I'm taking a Greyhound on the Hudson River line", "I'm in a New York state of mind",
    "and I don't want to waste more time, I'm in a New York state of mind",
    "across 110th Street… you can find it all in the street", "Spanish Harlem",
    "but now I know that rose trees never grow in New York City", "this Broadway's got… it's got a lot of songs to sing",
    "Williamsburg", "DUMBO", "Rockefeller Center", "Meatpacking District", "42nd Street", "The Dakota", "The Met Cloisters",
    "Little Odessa", "Astoria", "The High Line", "Union Square", "Washington Square Park", "Madison Square Garden",
    "The Flatiron", "Battery Park", "Riverside Drive", "Hell's Kitchen", "Chelsea", "Long Island City",
    "St. Patrick's Cathedral", "Carnegie Hall", "Madison Square Park", "The Bowery Ballroom", "Times Square New Year's Eve",
    "New York Fashion Week", "Park Avenue", "Tribeca Film Festival"
];